# Generated by Django 5.0.1 on 2024-01-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(default=1, max_length=24),
            preserve_default=False,
        ),
    ]
