# Generated by Django 5.0.1 on 2024-01-18 15:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now', models.BooleanField(verbose_name='경기상태')),
                ('attack_num', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='공격숫자')),
                ('defend_num', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='수비숫자')),
                ('attack_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_games', to=settings.AUTH_USER_MODEL, verbose_name='공격자')),
                ('defend_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defend_games', to=settings.AUTH_USER_MODEL, verbose_name='수비자')),
            ],
        ),
    ]
