# Generated by Django 5.0.1 on 2024-01-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='now',
            field=models.BooleanField(default=False, verbose_name='경기상태'),
        ),
    ]
