# Generated by Django 5.0.1 on 2024-01-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_attack_num_alter_game_defend_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='attack_user',
            field=models.CharField(default=0, max_length=20, verbose_name='공격자'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='defend_user',
            field=models.CharField(default=0, max_length=20, verbose_name='수비자'),
            preserve_default=False,
        ),
    ]
