# Generated by Django 5.0.1 on 2024-01-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_now'),
        ('game', '0002_game_game_num_alter_game_now'),
    ]

    operations = [
    ]
